; Tile index $100
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $101
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $102
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $103
.db $F0 $F0 $0F $FF $EF $E0 $1F $FF $DF $C0 $3F $FF $BF $80 $7F $FF $BF $80 $7F $FF $7F $00 $FF $FF $7F $00 $FF $FF $7F $00 $FF $FF
; Tile index $104
.db $FF $FF $00 $FF $3F $3F $C0 $FF $8F $0F $F0 $FF $C7 $07 $F8 $FF $C7 $07 $F8 $FF $E0 $00 $FF $FF $E7 $00 $FF $FF $EF $00 $FF $FF
; Tile index $105
.db $FF $FF $00 $FF $F0 $F0 $0F $FF $EF $E0 $1F $FF $DF $C0 $3F $FF $DF $C0 $3F $FF $1F $00 $FF $FF $9F $00 $FF $FF $DF $00 $FF $FF
; Tile index $106
.db $FF $FF $00 $FF $7F $7F $80 $FF $3F $3F $C0 $FF $9F $1F $E0 $FF $93 $13 $EC $FF $CD $01 $FE $FF $DC $00 $FF $FF $C8 $00 $FF $FF
; Tile index $107
.db $F8 $F8 $07 $FF $F7 $F0 $0F $FF $F7 $F0 $0F $FF $F7 $F0 $0F $FF $C0 $C0 $3F $FF $07 $07 $F8 $FF $E3 $E3 $1C $FF $F8 $F8 $07 $FF
; Tile index $108
.db $7F $00 $FF $FF $7F $00 $FF $FF $FF $00 $FF $FF $8C $00 $FF $FF $01 $01 $FE $FF $FC $FC $03 $FF $C1 $C1 $3E $FF $07 $07 $F8 $FF
; Tile index $109
.db $FF $00 $FF $FF $BF $00 $FF $FF $3F $00 $FF $FF $1F $00 $FF $FF $C0 $C0 $3F $FF $3F $3F $C0 $FF $C7 $C7 $38 $FF $F0 $F0 $0F $FF
; Tile index $10A
.db $EF $00 $FF $FF $E7 $00 $FF $FF $E7 $00 $FF $FF $83 $00 $FF $FF $18 $18 $E7 $FF $F0 $F0 $0F $FF $C3 $C3 $3C $FF $0F $0F $F0 $FF
; Tile index $10B
.db $DE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $E0 $00 $FF $FF $0F $0F $F0 $FF $3E $3E $C1 $FF $C0 $C0 $3F $FF $FF $FF $00 $FF
; Tile index $10C
.db $FF $FF $00 $FF $3F $3F $C0 $FF $DF $1F $E0 $FF $0F $0F $F0 $FF $80 $80 $7F $FF $03 $03 $FC $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $10D
.db $FF $FF $00 $FF $FF $FF $03 $FC $FF $FF $3B $C4 $FF $FF $3F $C0 $FF $FF $1F $E0 $FF $FF $7F $80 $FF $FF $7F $80 $FF $FF $3F $C0
; Tile index $10E
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $10F
.db $FC $FC $FC $03 $FE $FE $FE $01 $FE $FE $FE $01 $F8 $F8 $F8 $07 $FF $FF $FF $00 $FF $FF $FF $00 $FE $FE $FE $01 $F8 $F8 $F8 $07
; Tile index $110
.db $FF $FF $00 $FF $3F $3F $00 $FF $23 $23 $00 $FF $03 $03 $00 $FF $07 $07 $00 $FF $01 $01 $00 $FF $01 $01 $00 $FF $03 $03 $00 $FF
; Tile index $111
.db $FF $FF $7F $80 $FF $FF $7F $80 $9F $9F $1F $E0 $FF $FF $3F $C0 $3F $3F $3F $C0 $37 $37 $37 $C8 $86 $86 $06 $F9 $E0 $E0 $00 $FF
; Tile index $112
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $77 $77 $77 $88 $76 $76 $76 $89 $30 $30 $30 $CF
; Tile index $113
.db $FE $FE $FE $01 $FE $FE $FE $01 $F8 $F8 $F8 $07 $FC $FC $FC $03 $FC $FC $FC $03 $EC $EC $EC $13 $60 $60 $60 $9F $00 $00 $00 $FF
; Tile index $114
.db $03 $03 $00 $FF $01 $01 $00 $FF $01 $01 $00 $FF $07 $07 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $01 $01 $00 $FF $07 $07 $00 $FF
; Tile index $115
.db $80 $80 $00 $FF $80 $80 $00 $FF $E0 $E0 $00 $FF $C0 $C0 $00 $FF $C0 $C0 $00 $FF $C8 $C8 $00 $FF $F9 $F9 $00 $FF $FF $FF $00 $FF
; Tile index $116
.db $00 $00 $00 $FF $03 $03 $03 $FC $3B $3B $3B $C4 $3F $3F $3F $C0 $1F $1F $1F $E0 $7F $7F $7F $80 $7F $7F $7F $80 $3F $3F $3F $C0
; Tile index $117
.db $FF $FF $0C $F3 $FF $FF $6E $91 $FF $FF $EE $11 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $118
.db $F8 $80 $00 $87 $F9 $80 $00 $86 $FF $E0 $00 $E0 $FF $C0 $00 $C0 $FF $C0 $00 $C0 $FF $C8 $00 $C8 $FF $F9 $00 $F9 $FF $FF $00 $FF
; Tile index $119
.db $C3 $00 $00 $3C $C7 $00 $00 $38 $FF $00 $00 $00 $F8 $07 $00 $00 $FC $03 $00 $00 $FE $01 $00 $00 $FF $00 $00 $00 $FF $C0 $00 $C0
; Tile index $11A
.db $88 $00 $00 $77 $89 $00 $00 $76 $9F $00 $00 $60 $FF $00 $00 $00 $3F $C0 $00 $00 $E7 $F8 $00 $00 $78 $DF $20 $00 $BD $67 $18 $00
; Tile index $11B
.db $81 $00 $00 $7E $89 $00 $00 $76 $9F $00 $00 $60 $E3 $1C $00 $00 $97 $78 $00 $00 $7E $F1 $00 $00 $EB $D7 $20 $00 $E6 $3F $C0 $00
; Tile index $11C
.db $87 $00 $00 $78 $C7 $00 $00 $38 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $1F $E0 $00 $00 $7F $80 $00 $00 $FF $03 $00 $03
; Tile index $11D
.db $F1 $FF $00 $F1 $F8 $FF $00 $F8 $FD $FF $00 $FC $FE $FF $00 $FE $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $11E
.db $BF $F2 $0D $80 $BF $F2 $0D $80 $FF $FA $05 $40 $FF $FA $05 $00 $7F $FA $05 $00 $FF $DA $25 $80 $FF $EA $15 $80 $FF $EA $15 $C0
; Tile index $11F
.db $FD $3F $C0 $01 $FB $6F $90 $03 $FA $6F $90 $02 $F8 $5F $A0 $00 $F0 $5F $A0 $00 $F1 $5F $A0 $01 $F1 $5F $A0 $01 $F3 $5F $A0 $03
; Tile index $120
.db $C7 $FF $00 $C7 $0F $FF $00 $0F $3F $FF $00 $3F $7F $FF $00 $7F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $121
.db $88 $00 $00 $77 $8C $00 $00 $73 $9F $00 $00 $60 $FF $00 $00 $00 $3F $C0 $00 $00 $E7 $F8 $00 $00 $78 $DF $20 $00 $BD $6F $10 $00
; Tile index $122
.db $71 $00 $00 $8E $79 $00 $00 $86 $FF $00 $00 $00 $E3 $1C $00 $00 $97 $78 $00 $00 $7E $F1 $00 $00 $EB $D7 $20 $00 $E6 $BF $40 $00
; Tile index $123
.db $FF $F2 $0D $C0 $FF $F2 $0D $C0 $FF $F2 $0D $C0 $FF $F2 $0D $C0 $FF $F2 $0D $C0 $FF $F2 $0D $C0 $FF $F2 $0D $C0 $FF $F2 $0D $C0
; Tile index $124
.db $F3 $5F $A0 $03 $F3 $5F $A0 $03 $F3 $5F $A0 $03 $F3 $5F $A0 $03 $F3 $5F $A0 $03 $F3 $5F $A0 $03 $F3 $5F $A0 $03 $F3 $5F $A0 $03
; Tile index $125
.db $FF $F3 $0F $FC $FF $F3 $7F $8C $FF $C0 $3F $F3 $FF $C0 $3F $F3 $EF $E3 $EF $1C $FF $F3 $7F $8C $F7 $FF $3F $C0 $C2 $DF $1F $E0
; Tile index $126
.db $1F $FF $E0 $1F $9F $DF $DC $23 $BF $BF $B8 $47 $1F $E7 $F8 $1F $BF $E7 $FF $18 $FF $81 $FE $67 $7F $81 $FE $67 $7F $E7 $FC $1B
; Tile index $127
.db $FF $F6 $09 $C0 $FF $F6 $09 $C0 $FF $F4 $0B $C0 $FF $E4 $1B $C0 $FF $E4 $1B $C0 $FF $CC $33 $80 $F7 $D9 $26 $80 $E7 $B9 $46 $00
; Tile index $128
.db $F3 $5F $A0 $03 $F3 $5F $A0 $03 $F3 $5F $A0 $03 $F3 $DF $20 $03 $FB $DF $20 $03 $79 $EF $10 $01 $3D $EF $10 $01 $1E $E7 $18 $00
; Tile index $129
.db $F7 $F4 $77 $8B $EF $EC $EF $13 $8F $80 $0F $FC $FF $F0 $7F $8C $E7 $E4 $E7 $1B $03 $00 $03 $FF $C0 $C0 $00 $FF $E0 $E0 $00 $FF
; Tile index $12A
.db $5F $C7 $DE $39 $E7 $E7 $E7 $18 $C3 $03 $C0 $FF $CF $0F $CE $F1 $07 $07 $07 $F8 $00 $00 $00 $FF $03 $03 $00 $FF $07 $07 $00 $FF
; Tile index $12B
.db $10 $FF $FF $00 $00 $DF $DF $20 $00 $8F $8F $70 $E0 $E7 $E7 $18 $D8 $DB $DB $24 $BE $BF $BF $40 $FF $7F $7F $00 $FF $3F $3F $00
; Tile index $12C
.db $10 $FF $FF $00 $00 $F7 $F7 $08 $00 $E3 $E3 $1C $0E $CF $CF $30 $3F $BF $BF $40 $BF $BF $BF $40 $FF $DF $DF $00 $FF $8E $8E $00
; Tile index $12D
.db $7F $1F $1F $80 $1F $0E $0E $E0 $14 $04 $04 $EB $20 $00 $00 $DF $70 $00 $00 $8F $18 $E0 $00 $07 $04 $F8 $00 $03 $00 $FE $00 $01
; Tile index $12E
.db $C4 $04 $04 $3B $20 $00 $00 $DF $10 $00 $00 $EF $08 $00 $00 $F7 $1C $00 $00 $E3 $30 $0E $00 $C1 $40 $3F $00 $80 $00 $FF $00 $00
; Tile index $12F
.db $F7 $0F $F0 $00 $F7 $1F $E0 $00 $EF $1F $E0 $00 $EF $1F $E0 $00 $EF $1F $E0 $00 $EF $1F $E0 $00 $F7 $1F $E0 $00 $F7 $0F $F0 $00
; Tile index $130
.db $FF $F0 $0F $00 $FF $E0 $1F $00 $FF $E0 $1F $00 $FF $E0 $1F $00 $FF $E0 $1F $00 $FF $E0 $1F $00 $FF $E0 $1F $00 $FF $F0 $0F $00
