; Tile index $000
.db $10 $FF $FF $00 $00 $F7 $F7 $08 $00 $E3 $E3 $1C $0E $CF $CF $30 $3F $BF $BF $40 $BF $BF $BF $40 $FF $DF $DF $00 $FF $8E $8E $00
; Tile index $001
.db $10 $FF $FF $00 $00 $DF $DF $20 $00 $8F $8F $70 $E0 $E7 $E7 $18 $D8 $DB $DB $24 $BE $BF $BF $40 $FF $7F $7F $00 $FF $3F $3F $00
; Tile index $002
.db $10 $FF $FF $00 $00 $F7 $F7 $08 $00 $E3 $E3 $1C $0C $CD $CD $32 $3E $BE $BE $41 $BE $BF $BE $40 $FF $DF $DF $00 $FE $9E $9E $01
; Tile index $003
.db $01 $E1 $EE $10 $01 $C1 $DE $20 $02 $83 $BC $40 $0D $0E $70 $80 $F0 $FF $00 $00 $00 $FF $00 $00 $FF $80 $80 $03 $3F $07 $00 $C7
; Tile index $004
.db $80 $80 $7F $00 $80 $80 $7F $00 $40 $C0 $3F $00 $B0 $70 $0F $00 $0F $FF $00 $00 $00 $FF $00 $00 $FF $00 $00 $FF $FF $FF $00 $FF
; Tile index $005
.db $01 $01 $FE $00 $01 $01 $FE $00 $02 $03 $FC $00 $0D $0E $F0 $00 $F0 $FF $00 $00 $00 $FF $00 $00 $FF $00 $00 $FF $FF $FF $00 $FF
; Tile index $006
.db $80 $87 $77 $08 $80 $83 $7B $04 $40 $C1 $3D $02 $B0 $70 $0E $01 $0F $FF $00 $00 $00 $FF $00 $00 $FF $01 $01 $C0 $FC $E0 $00 $E3
; Tile index $007
.db $08 $FF $FF $00 $00 $EF $EF $10 $00 $C7 $C7 $38 $30 $B3 $B3 $4C $7C $7D $7D $82 $7D $FD $7D $02 $FF $FB $FB $00 $7F $79 $79 $80
; Tile index $008
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $01 $00 $FF $FF $00 $FE $01 $01 $FE $FF $FE $00 $FF $FF $FF
; Tile index $009
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FC $00 $FF $FF $E0 $03 $FC $FC $03 $1F $E3 $E0 $1F $FF $1F
; Tile index $00A
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $00B
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $00C
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $07 $00 $FF $FF $00 $F8 $07 $07 $F8 $FF $F8 $00 $FF $FF $FF
; Tile index $00D
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $7F $00 $FF $FF $3F $80 $7F
; Tile index $00E
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $00F
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $010
.db $FF $00 $FF $FF $FF $80 $7F $FF $FF $F8 $07 $FF $FF $FE $01 $FF $FF $FC $03 $FF $FF $FE $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $011
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FB $FF $FF $00 $C2 $FF $C7 $38 $87 $C7 $CF $30 $81 $CF $DF $A0 $06 $DF $9F $60 $0E $9F
; Tile index $012
.db $FF $00 $FF $FF $FF $00 $3F $FF $3F $C0 $00 $3F $00 $FF $00 $00 $9F $60 $00 $9F $9F $60 $1F $9F $9F $60 $1F $9F $1F $E0 $07 $1F
; Tile index $013
.db $FF $00 $FF $FF $FF $03 $FC $FF $FF $03 $FC $FF $FF $00 $08 $FF $08 $F7 $08 $08 $FF $00 $F8 $FF $FF $00 $F8 $FF $FF $00 $F8 $FF
; Tile index $014
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $1E $00 $FF $00 $3C $20 $DF $00 $6C $40 $BF $00 $84 $80 $7F $00 $02 $02 $FD $00
; Tile index $015
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $01 $00 $FF $00 $02 $02 $FD $00 $03 $01 $FE $00 $03 $00 $FF $00 $06 $04 $FB $00
; Tile index $016
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $1E $00 $FF $00 $3C $20 $DF $00 $6C $40 $BF $00 $84 $80 $7F $00 $02 $02 $FD $00
; Tile index $017
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $07 $07 $07 $F8 $03 $03 $03 $FC $01 $03 $01 $FE $00 $03 $01 $FE $00 $07 $05 $FA $00
; Tile index $018
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $E0 $E0 $E0 $1F $C0 $C0 $C0 $3F $80 $C0 $80 $7F $00 $C0 $80 $7F $00 $E0 $A0 $5F $00
; Tile index $019
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $78 $00 $FF $00 $3C $04 $FB $00 $36 $02 $FD $00 $21 $01 $FE $00 $40 $40 $BF $00
; Tile index $01A
.db $FF $FF $00 $FF $FF $FF $C0 $3F $FF $FF $DC $23 $FF $FF $FC $03 $FF $FF $F8 $07 $FF $FF $FE $01 $FF $FF $FE $01 $FF $FF $FC $03
; Tile index $01B
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $01C
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $38 $C7 $FB $FB $F9 $06 $F9 $F9 $F9 $06 $FF $FF $FF $00
; Tile index $01D
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $C0 $3F $F3 $F3 $F0 $0F $F5 $F5 $F5 $0A $FC $FC $FC $03
; Tile index $01E
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FF $FE $F0 $81 $7F $F0 $80 $8F $7F
; Tile index $01F
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $1F $00 $E0 $FF $21 $1E $DE $DF
; Tile index $020
.db $C4 $04 $04 $3B $20 $00 $00 $DF $10 $00 $00 $EF $08 $00 $00 $F7 $1C $00 $00 $E3 $30 $0E $00 $C1 $40 $3F $00 $80 $00 $FF $00 $00
; Tile index $021
.db $7F $1F $1F $80 $1F $0E $0E $E0 $14 $04 $04 $EB $20 $00 $00 $DF $70 $00 $00 $8F $18 $E0 $00 $07 $04 $F8 $00 $03 $00 $FE $00 $01
; Tile index $022
.db $CD $0C $0C $32 $2A $09 $08 $D4 $14 $03 $00 $E8 $08 $07 $00 $F0 $18 $07 $00 $E0 $30 $0F $00 $C0 $40 $3F $00 $80 $00 $FF $00 $00
; Tile index $023
.db $FC $03 $00 $07 $1F $E0 $00 $03 $03 $FC $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $024
.db $00 $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $025
.db $00 $FF $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $026
.db $3F $C0 $00 $E0 $F8 $07 $00 $C0 $C0 $3F $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $027
.db $B3 $30 $30 $4C $54 $90 $10 $2B $28 $C0 $00 $17 $10 $E0 $00 $0F $18 $E0 $00 $07 $0C $F0 $00 $03 $02 $FC $00 $01 $00 $FF $00 $00
; Tile index $028
.db $00 $FF $FF $FF $FF $00 $00 $FF $FF $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $029
.db $00 $FF $FF $FF $FF $00 $00 $FF $FF $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $02A
.db $00 $FF $FF $FF $FF $00 $00 $FF $FF $FF $FF $FF $00 $FF $FF $FF $1F $F0 $F0 $FF $3F $EF $E0 $FF $3F $EF $E0 $FF $3F $EF $E0 $FF
; Tile index $02B
.db $00 $FF $FF $FF $FF $00 $00 $FF $FF $FF $FF $FF $00 $FF $FF $FF $C0 $3F $3F $FF $F0 $8F $0F $FF $F8 $C7 $07 $FF $F8 $C7 $07 $FF
; Tile index $02C
.db $00 $FF $FF $FF $FF $00 $00 $FF $FF $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $02D
.db $7F $9F $C0 $BF $DF $2F $20 $FF $EF $F7 $F0 $FF $1F $E7 $F0 $EF $1F $E7 $F0 $EF $1F $E7 $F0 $EF $1F $E7 $F0 $EF $1F $E7 $F0 $EF
; Tile index $02E
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $02F
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $030
.db $FF $FF $00 $FF $FF $FE $00 $FF $FE $FD $00 $FE $FE $FD $00 $FE $FC $FB $00 $FC $F9 $F6 $00 $F9 $F3 $EC $00 $F3 $E7 $98 $00 $E7
; Tile index $031
.db $BF $40 $1F $BF $7F $80 $1E $7F $7E $81 $06 $7E $FE $01 $06 $FE $FE $01 $0E $FE $FE $01 $06 $FE $FC $03 $00 $FC $F9 $06 $00 $F9
; Tile index $032
.db $3F $C0 $0F $3F $3F $C0 $0F $3F $7F $80 $0F $7F $7F $80 $1F $7F $7F $80 $1F $7F $FF $00 $1E $FF $FF $00 $3C $FF $FF $00 $3C $FF
; Tile index $033
.db $FF $00 $F8 $FF $FF $00 $F0 $FF $FE $00 $E1 $FE $FE $00 $81 $FE $FE $00 $01 $FE $FC $00 $03 $FC $F8 $00 $07 $F8 $F8 $00 $07 $F8
; Tile index $034
.db $03 $01 $FE $00 $06 $04 $FB $00 $0C $08 $F7 $00 $3C $30 $CF $00 $FE $C2 $3D $00 $1E $00 $FF $00 $08 $00 $FF $00 $08 $00 $FF $00
; Tile index $035
.db $0C $08 $F7 $00 $18 $10 $EF $00 $34 $24 $DB $00 $62 $42 $BD $00 $E1 $81 $7E $00 $23 $02 $FD $00 $14 $14 $EB $00 $1C $00 $FF $00
; Tile index $036
.db $03 $01 $FE $00 $06 $04 $FB $00 $0C $08 $F7 $00 $3C $30 $CF $00 $FE $C2 $3D $00 $1E $00 $FF $00 $08 $00 $FF $00 $08 $00 $FF $00
; Tile index $037
.db $0D $09 $F6 $00 $19 $11 $EE $00 $35 $25 $DA $00 $63 $43 $BC $00 $E1 $81 $7E $00 $23 $03 $FC $00 $15 $15 $EA $00 $1D $01 $FE $00
; Tile index $038
.db $B0 $90 $6F $00 $98 $88 $77 $00 $AC $A4 $5B $00 $C6 $C2 $3D $00 $87 $81 $7E $00 $C4 $C0 $3F $00 $A8 $A8 $57 $00 $B8 $80 $7F $00
; Tile index $039
.db $C0 $80 $7F $00 $60 $20 $DF $00 $30 $10 $EF $00 $3C $0C $F3 $00 $7F $43 $BC $00 $78 $00 $FF $00 $10 $00 $FF $00 $10 $00 $FF $00
; Tile index $03A
.db $FF $FF $FE $01 $FF $FF $FE $01 $F9 $F9 $F8 $07 $FF $FF $FC $03 $FC $FC $FC $03 $EC $EC $EC $13 $61 $61 $60 $9F $07 $07 $00 $FF
; Tile index $03B
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $03C
.db $3F $3F $3F $C0 $1F $1F $1F $E0 $FF $00 $00 $FF $00 $00 $FF $FF $00 $FF $00 $FF $FF $00 $00 $FF $AA $FF $FF $FF $55 $FF $FF $FF
; Tile index $03D
.db $FE $FE $FE $01 $FE $FE $FE $01 $FE $00 $00 $FF $01 $00 $FE $FF $00 $FE $01 $FF $FE $00 $01 $FF $AA $FC $FD $FF $56 $FC $FD $FF
; Tile index $03E
.db $40 $3F $00 $FF $40 $00 $3F $FF $80 $12 $6D $FF $80 $7F $00 $FF $80 $00 $7F $FF $80 $7F $00 $FF $80 $7F $00 $FF $7F $00 $80 $BF
; Tile index $03F
.db $5E $BF $3F $FF $5F $3F $BF $FF $BF $7F $7F $FF $FF $79 $79 $FF $FF $79 $79 $FF $FD $7B $79 $FD $FF $7F $7F $FF $FF $3F $3F $FF
; Tile index $040
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $041
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $042
.db $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF
; Tile index $043
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $044
.db $00 $FF $FF $FF $00 $FF $FF $FF $3B $FF $FF $C4 $3F $FF $FF $C0 $1F $FF $FF $E0 $7F $FF $FF $80 $7F $FF $FF $80 $3F $FF $FF $C0
; Tile index $045
.db $00 $FF $FF $FF $00 $FF $FF $FF $DC $FF $FF $23 $FC $FF $FF $03 $F8 $FF $FF $07 $FE $FF $FF $01 $FE $FF $FF $01 $FC $FF $FF $03
; Tile index $046
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $047
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $048
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $049
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $04A
.db $3F $DF $C0 $FF $7F $DF $C0 $FF $7F $DF $C0 $FF $7F $DF $C0 $FF $7F $DF $C0 $FF $7F $DF $C0 $FF $7F $DF $C0 $FF $FF $BF $80 $FF
; Tile index $04B
.db $FC $E3 $03 $FF $FC $E3 $03 $FF $FC $E3 $03 $FF $FE $F1 $01 $FF $FE $F1 $01 $FF $FE $F1 $01 $FF $FE $F1 $01 $FF $FE $F1 $01 $FF
; Tile index $04C
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $04D
.db $0F $F3 $F8 $F7 $07 $F9 $FC $FB $07 $F9 $FC $FB $07 $F9 $FC $FB $07 $F9 $FC $FB $07 $F9 $FC $FB $07 $F9 $FC $FB $07 $F9 $FC $FB
; Tile index $04E
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $04F
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $050
.db $98 $88 $77 $00 $88 $80 $7F $00 $98 $90 $6F $00 $F8 $E0 $1F $00 $FC $84 $7B $00 $8C $80 $7F $00 $86 $82 $7D $00 $86 $80 $7F $00
; Tile index $051
.db $10 $00 $FF $00 $10 $00 $FF $00 $18 $08 $F7 $00 $1C $04 $FB $00 $0F $03 $FC $00 $07 $00 $FF $00 $07 $00 $FF $00 $06 $00 $FF $00
; Tile index $052
.db $08 $00 $FF $00 $08 $00 $FF $00 $18 $10 $EF $00 $38 $20 $DF $00 $F0 $C0 $3F $00 $E0 $00 $FF $00 $E0 $00 $FF $00 $60 $00 $FF $00
; Tile index $053
.db $18 $10 $EF $00 $10 $00 $FF $00 $18 $08 $F7 $00 $1E $06 $F9 $00 $3F $21 $DE $00 $31 $00 $FF $00 $60 $40 $BF $00 $60 $00 $FF $00
; Tile index $054
.db $08 $00 $FF $00 $08 $00 $FF $00 $18 $10 $EF $00 $38 $20 $DF $00 $F0 $C0 $3F $00 $E0 $00 $FF $00 $E0 $00 $FF $00 $60 $00 $FF $00
; Tile index $055
.db $18 $10 $EF $00 $10 $00 $FF $00 $18 $08 $F7 $00 $1E $06 $F9 $00 $3F $21 $DE $00 $31 $00 $FF $00 $60 $40 $BF $00 $60 $00 $FF $00
; Tile index $056
.db $08 $00 $FF $00 $08 $00 $FF $00 $18 $10 $EF $00 $38 $20 $DF $00 $F0 $C0 $3F $00 $E0 $00 $FF $00 $E0 $00 $FF $00 $60 $00 $FF $00
; Tile index $057
.db $19 $11 $EE $00 $11 $01 $FE $00 $19 $09 $F6 $00 $1F $07 $F8 $00 $3F $21 $DE $00 $31 $01 $FE $00 $61 $41 $BE $00 $61 $01 $FE $00
; Tile index $058
.db $00 $FF $00 $00 $FF $00 $FF $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $059
.db $00 $FF $00 $00 $FF $00 $FF $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $05A
.db $0C $FF $00 $0C $F3 $0C $F3 $00 $0C $F3 $FF $F3 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $05B
.db $7F $FF $00 $7F $BE $7F $80 $3E $BE $7F $80 $3E $BE $7F $80 $3E $BE $7F $80 $3E $40 $BF $C0 $80 $5E $A1 $DE $80 $5D $A2 $DD $80
; Tile index $05C
.db $0C $FF $00 $0C $F3 $0C $F3 $00 $0C $F3 $FF $F3 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $05D
.db $0C $FF $00 $0C $71 $8E $71 $00 $8A $75 $FB $71 $04 $FB $FF $FB $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $05E
.db $1C $E3 $1C $00 $00 $FF $00 $00 $80 $7F $83 $03 $60 $9F $E7 $87 $18 $E7 $FB $E3 $00 $FF $FB $FB $04 $FB $FD $F9 $02 $FD $FE $FC
; Tile index $05F
.db $3C $C3 $3C $00 $00 $FF $00 $00 $00 $FF $C3 $C3 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $060
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $061
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $062
.db $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $FF $00 $00 $FF
; Tile index $063
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $00 $00 $FF
; Tile index $064
.db $7F $FF $FF $80 $7F $FF $FF $80 $1F $9F $9F $E0 $FF $FF $FF $C0 $3F $3F $3F $C0 $37 $37 $37 $C8 $86 $86 $86 $F9 $E0 $00 $00 $FF
; Tile index $065
.db $FE $FF $FF $01 $FE $FF $FF $01 $F8 $F9 $F9 $07 $FF $FF $FF $03 $FC $FC $FC $03 $EC $EC $EC $13 $61 $61 $61 $9F $07 $00 $00 $FF
; Tile index $066
.db $00 $FF $FF $FF $FF $00 $00 $FF $FF $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $067
.db $00 $FF $FF $FF $FF $00 $00 $FF $FF $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $068
.db $00 $FF $FF $FF $88 $FF $FF $FF $55 $FF $FF $FF $AA $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $00 $FF
; Tile index $069
.db $00 $FF $FF $FF $88 $FF $FF $FF $55 $FF $FF $FF $AA $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $00 $FF
; Tile index $06A
.db $FF $BF $80 $FF $FF $BF $80 $FF $FF $BF $80 $FF $FF $BF $80 $FF $FF $BF $80 $FF $FF $BF $80 $FF $C0 $80 $80 $FF $FF $00 $00 $FF
; Tile index $06B
.db $FE $F1 $01 $FF $FF $F1 $01 $FF $FF $F1 $01 $FF $FF $F1 $01 $FF $FF $F1 $01 $FF $FF $F1 $01 $FF $0F $01 $01 $FF $FF $00 $00 $FF
; Tile index $06C
.db $00 $FF $FF $FF $44 $FF $FF $FF $AA $FF $FF $FF $55 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $00 $00 $FF
; Tile index $06D
.db $03 $FD $FC $FF $47 $FD $FC $FF $AB $FE $FE $FF $55 $FE $FE $FF $FF $FE $FE $FF $FF $FE $FE $FF $FF $FE $FE $FF $FF $00 $00 $FF
; Tile index $06E
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $06F
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $070
.db $83 $81 $7E $00 $81 $80 $7F $00 $80 $80 $7F $00 $80 $80 $7F $00 $80 $80 $7F $00 $C0 $C0 $3F $00 $E0 $A0 $5F $00 $B0 $D3 $2C $00
; Tile index $071
.db $06 $00 $FF $00 $8F $89 $76 $00 $FF $70 $8F $00 $79 $00 $FF $00 $30 $00 $FF $00 $30 $00 $FF $00 $10 $00 $FF $00 $10 $C3 $3C $00
; Tile index $072
.db $60 $00 $FF $00 $F1 $91 $6E $00 $FF $0E $F1 $00 $00 $FF $00 $00 $01 $F9 $06 $00 $09 $C9 $36 $00 $49 $C9 $36 $00 $49 $C9 $36 $00
; Tile index $073
.db $C0 $80 $7F $00 $80 $00 $FF $00 $00 $00 $FF $00 $00 $FF $00 $00 $80 $9F $60 $00 $90 $93 $6C $00 $92 $93 $6C $00 $92 $93 $6C $00
; Tile index $074
.db $60 $00 $FF $00 $F1 $91 $6E $00 $FF $0E $F1 $00 $9E $00 $FF $00 $0C $00 $FF $00 $0C $00 $FF $00 $08 $00 $FF $00 $08 $C3 $3C $00
; Tile index $075
.db $C0 $80 $7F $00 $80 $00 $FF $00 $00 $00 $FF $00 $01 $01 $FE $00 $01 $00 $FF $00 $03 $02 $FD $00 $06 $04 $FB $00 $0C $CB $34 $00
; Tile index $076
.db $60 $00 $FF $00 $F1 $91 $6E $00 $FF $0E $F1 $00 $9E $00 $FF $00 $0C $00 $FF $00 $0C $00 $FF $00 $08 $00 $FF $00 $08 $C3 $3C $00
; Tile index $077
.db $C1 $81 $7E $00 $81 $01 $FE $00 $01 $01 $FE $00 $01 $01 $FE $00 $01 $01 $FE $00 $03 $03 $FC $00 $07 $05 $FA $00 $0D $CB $34 $00
; Tile index $078
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00
; Tile index $079
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00
; Tile index $07A
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00
; Tile index $07B
.db $5C $A3 $DD $81 $AC $53 $AD $01 $A0 $5F $A1 $01 $6C $9F $ED $8D $2C $DF $ED $CD $14 $EF $F5 $E5 $0A $F5 $FB $F1 $00 $FF $00 $00
; Tile index $07C
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00
; Tile index $07D
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00
; Tile index $07E
.db $00 $FF $FE $FE $00 $FF $FE $FE $01 $FE $FF $FE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00
; Tile index $07F
.db $00 $00 $FF $00 $00 $FF $00 $00 $00 $FF $3F $3F $C0 $3F $CF $0F $30 $CF $F7 $C7 $00 $FF $F7 $F7 $00 $FF $F0 $F0 $00 $FF $00 $00
; Tile index $080
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $081
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $082
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $083
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $084
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $085
.db $F8 $F8 $07 $FF $F7 $F0 $0F $FF $F7 $F0 $0F $FF $F7 $F0 $0F $FF $C0 $C0 $3F $FF $07 $07 $F8 $FF $E3 $E3 $1C $FF $F8 $F8 $07 $FF
; Tile index $086
.db $7F $00 $FF $FF $7F $00 $FF $FF $FF $00 $FF $FF $8C $00 $FF $FF $01 $01 $FE $FF $FC $FC $03 $FF $C1 $C1 $3E $FF $07 $07 $F8 $FF
; Tile index $087
.db $FF $00 $FF $FF $BF $00 $FF $FF $3F $00 $FF $FF $1F $00 $FF $FF $C0 $C0 $3F $FF $3F $3F $C0 $FF $C7 $C7 $38 $FF $F0 $F0 $0F $FF
; Tile index $088
.db $EF $00 $FF $FF $E7 $00 $FF $FF $E7 $00 $FF $FF $81 $00 $FF $FD $18 $18 $E7 $FF $F0 $F0 $0F $FF $C3 $C3 $3C $FF $0F $0F $F0 $FF
; Tile index $089
.db $DE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $E0 $00 $FF $FF $0F $0F $F0 $FF $3E $3E $C1 $FF $C0 $C0 $3F $FF $FF $FF $00 $FF
; Tile index $08A
.db $FF $FF $00 $FF $3F $3F $C0 $FF $DF $1F $E0 $FF $0F $0F $F0 $FF $80 $80 $7F $FF $03 $03 $FC $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08B
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08C
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08D
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08E
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08F
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $090
.db $1C $E3 $1C $00 $00 $FF $00 $00 $00 $FF $63 $63 $00 $FF $7F $7F $00 $FF $7F $7F $00 $FF $7F $7F $00 $FF $7F $7F $00 $FF $7F $7F
; Tile index $091
.db $3C $C3 $3C $00 $00 $FF $00 $00 $00 $FF $C3 $C3 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $092
.db $49 $C9 $36 $00 $49 $C9 $36 $00 $49 $C9 $36 $00 $49 $C9 $36 $00 $49 $C9 $36 $00 $49 $C9 $36 $00 $49 $C9 $36 $00 $49 $C9 $36 $00
; Tile index $093
.db $92 $93 $6C $00 $92 $93 $6C $00 $92 $93 $6C $00 $92 $93 $6C $00 $92 $93 $6C $00 $92 $93 $6C $00 $92 $93 $6C $00 $92 $93 $6C $00
; Tile index $094
.db $08 $C3 $3C $00 $00 $FF $00 $00 $00 $FF $C3 $C3 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $095
.db $1C $D3 $2C $00 $00 $FF $00 $00 $00 $FF $C3 $C3 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $096
.db $08 $C3 $3C $00 $00 $FF $00 $00 $00 $FF $C3 $C3 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $097
.db $1C $D3 $2C $00 $00 $FF $00 $00 $00 $FF $C2 $C2 $00 $FF $FE $FE $00 $FF $FE $FE $00 $FF $FE $FE $00 $FF $FE $FE $00 $FF $FE $FE
; Tile index $098
.db $3C $C3 $3C $00 $00 $FF $00 $00 $00 $FF $C3 $C3 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $099
.db $00 $EE $11 $00 $00 $EE $11 $00 $0E $EE $D1 $C0 $00 $E0 $DF $C0 $00 $EE $D1 $C0 $00 $EE $D1 $C0 $00 $EE $D1 $C0 $0E $EE $D1 $C0
; Tile index $09A
.db $00 $77 $88 $00 $00 $77 $88 $00 $70 $77 $8B $03 $00 $07 $FB $03 $00 $77 $8B $03 $00 $77 $8B $03 $00 $77 $8B $03 $70 $77 $8B $03
; Tile index $09B
.db $3C $C3 $3C $00 $00 $FF $00 $00 $00 $FF $C3 $C3 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $09C
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $09D
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $09E
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $F8 $00 $FF $FF $F0 $08 $FF $FF $F0 $06 $FF $FF $F8 $01 $FF $FF $FE
; Tile index $09F
.db $00 $FF $FF $FF $00 $FF $FF $FF $10 $FF $FF $E7 $00 $FF $FF $E7 $08 $FF $FF $47 $10 $FF $FF $0F $00 $FF $FF $1F $A0 $FF $FF $1F
; Tile index $0A0
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A1
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A2
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A3
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A4
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A5
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A6
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A7
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A8
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A9
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0AA
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0AB
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0AC
.db $F0 $F0 $0F $FF $EF $E0 $1F $FF $DF $C0 $3F $FF $BF $80 $7F $FF $BF $80 $7F $FF $7F $00 $FF $FF $7F $00 $FF $FF $7F $00 $FF $FF
; Tile index $0AD
.db $FF $FF $00 $FF $3F $3F $C0 $FF $8F $0F $F0 $FF $C7 $07 $F8 $FF $C7 $07 $F8 $FF $E0 $00 $FF $FF $E7 $00 $FF $FF $EF $00 $FF $FF
; Tile index $0AE
.db $FF $FF $00 $FF $F0 $F0 $0F $FF $EF $E0 $1F $FF $DF $C0 $3F $FF $DF $C0 $3F $FF $1F $00 $FF $FF $9F $00 $FF $FF $DF $00 $FF $FF
; Tile index $0AF
.db $FF $FF $00 $FF $7F $7F $80 $FF $3F $3F $C0 $FF $9F $1F $E0 $FF $93 $13 $EC $FF $CD $01 $FE $FF $DC $00 $FF $FF $C8 $00 $FF $FF
; Tile index $0B0
.db $00 $80 $7F $00 $00 $FF $00 $00 $00 $FF $7F $7F $00 $FF $7F $7F $00 $FF $7F $7F $00 $FF $7F $7F $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0B1
.db $00 $00 $FF $00 $00 $FF $00 $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0B2
.db $49 $C9 $36 $00 $49 $C9 $36 $00 $49 $C9 $36 $00 $49 $C9 $36 $00 $7F $FF $00 $00 $00 $FF $00 $00 $FF $FF $FF $FF $00 $FF $00 $00
; Tile index $0B3
.db $92 $93 $6C $00 $92 $93 $6C $00 $92 $93 $6C $00 $92 $93 $6C $00 $FE $FF $00 $00 $00 $FF $00 $00 $FF $FF $FF $FF $00 $FF $00 $00
; Tile index $0B4
.db $00 $00 $FF $00 $00 $FF $00 $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0B5
.db $00 $00 $FF $00 $00 $FF $00 $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0B6
.db $00 $00 $FF $00 $00 $FF $00 $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0B7
.db $00 $01 $FE $00 $00 $FF $00 $00 $00 $FF $FE $FE $00 $FF $FE $FE $00 $FF $FE $FE $00 $FF $FE $FE $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0B8
.db $00 $00 $FF $00 $00 $FF $00 $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0B9
.db $00 $20 $DF $00 $00 $FF $00 $00 $00 $FF $C0 $C0 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0BA
.db $00 $04 $FB $00 $00 $FF $00 $00 $00 $FF $03 $03 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0BB
.db $00 $00 $FF $00 $00 $FF $00 $00 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0BC
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0BD
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0BE
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $0BF
.db $00 $FF $FF $9F $40 $FF $FF $8F $20 $FF $FF $C7 $10 $FF $FF $E3 $01 $FF $FF $F0 $06 $FF $FF $F1 $00 $FF $00 $00 $00 $FF $00 $00
