; Tile index $000
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $001
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $002
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $F0 $0F $0F $0F $F0 $0F $0F $0F $F0 $0F $0F $0F $F0 $0F $0F $0F
; Tile index $003
.db $00 $F0 $F0 $F0 $00 $F0 $F0 $F0 $00 $F0 $F0 $F0 $00 $F0 $F0 $F0 $00 $F0 $F0 $F0 $00 $F0 $F0 $F0 $00 $F0 $F0 $F0 $00 $F0 $F0 $F0
; Tile index $004
.db $00 $0F $0F $0F $00 $0F $0F $0F $00 $0F $0F $0F $00 $0F $0F $0F $0F $00 $00 $00 $0F $00 $00 $00 $0F $00 $00 $00 $0F $00 $00 $00
; Tile index $005
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $F0 $F0 $00 $FF $F0 $F0 $00 $FF $F0 $F0 $00 $FF $F0 $F0
; Tile index $006
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $007
.db $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00
; Tile index $008
.db $00 $0F $FF $0F $00 $0F $FF $0F $00 $0F $FF $0F $00 $0F $FF $0F $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00
; Tile index $009
.db $00 $F0 $FF $F0 $00 $F0 $FF $F0 $00 $F0 $FF $F0 $00 $F0 $FF $F0 $00 $F0 $FF $F0 $00 $F0 $FF $F0 $00 $F0 $FF $F0 $00 $F0 $FF $F0
; Tile index $00A
.db $00 $0F $FF $0F $00 $0F $FF $0F $00 $0F $FF $0F $00 $0F $FF $0F $0F $00 $FF $00 $0F $00 $FF $00 $0F $00 $FF $00 $0F $00 $FF $00
; Tile index $00B
.db $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $00C
.db $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $00D
.db $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $0F $FF $FF $00 $0F $FF $FF $00 $0F $FF $FF $00 $0F $FF $FF $00
; Tile index $00E
.db $00 $FF $F0 $FF $00 $FF $F0 $FF $00 $FF $F0 $FF $00 $FF $F0 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $00F
.db $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $010
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $0F $FF $00 $FF $0F $FF $00 $FF $0F $FF $00 $FF $0F $FF
; Tile index $011
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $012
.db $00 $0F $FF $FF $00 $0F $FF $FF $00 $0F $FF $FF $00 $0F $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $013
.db $00 $F0 $FF $FF $00 $F0 $FF $FF $00 $F0 $FF $FF $00 $F0 $FF $FF $00 $F0 $FF $FF $00 $F0 $FF $FF $00 $F0 $FF $FF $00 $F0 $FF $FF
; Tile index $014
.db $00 $0F $FF $FF $00 $0F $FF $FF $00 $0F $FF $FF $00 $0F $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF
; Tile index $015
.db $0F $00 $00 $00 $0F $00 $00 $00 $0F $00 $00 $00 $0F $00 $00 $00 $0F $00 $00 $00 $0F $00 $00 $00 $0F $00 $00 $00 $0F $00 $00 $00
; Tile index $016
.db $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $017
.db $F0 $FF $00 $00 $F0 $FF $00 $00 $F0 $FF $00 $00 $F0 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $018
.db $0F $FF $00 $00 $0F $FF $00 $00 $0F $FF $00 $00 $0F $FF $00 $00 $0F $FF $00 $00 $0F $FF $00 $00 $0F $FF $00 $00 $0F $FF $00 $00
; Tile index $019
.db $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $F0 $00 $FF $00 $F0 $00 $FF $00 $F0 $00 $FF $00 $F0 $00 $FF $00
; Tile index $01A
.db $0F $00 $FF $00 $0F $00 $FF $00 $0F $00 $FF $00 $0F $00 $FF $00 $0F $00 $FF $00 $0F $00 $FF $00 $0F $00 $FF $00 $0F $00 $FF $00
; Tile index $01B
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F0 $FF $FF $00 $F0 $FF $FF $00 $F0 $FF $FF $00 $F0 $FF $FF $00
; Tile index $01C
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $01D
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F
; Tile index $01E
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $F0 $F0 $FF $00 $F0 $F0 $FF $00 $F0 $F0 $FF $00 $F0 $F0 $FF
; Tile index $01F
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF
; Tile index $020
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $F0 $FF $0F $FF $F0 $FF $0F $FF $F0 $FF $0F $FF $F0 $FF $0F $FF
; Tile index $021
.db $F0 $FF $00 $FF $F0 $FF $00 $FF $F0 $FF $00 $FF $F0 $FF $00 $FF $00 $FF $F0 $FF $00 $FF $F0 $FF $00 $FF $F0 $FF $00 $FF $F0 $FF
; Tile index $022
.db $0F $FF $00 $FF $0F $FF $00 $FF $0F $FF $00 $FF $0F $FF $00 $FF $0F $FF $00 $FF $0F $FF $00 $FF $0F $FF $00 $FF $0F $FF $00 $FF
; Tile index $023
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF
; Tile index $024
.db $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF
; Tile index $025
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $F0 $0F $0F $0F $F0 $0F $0F $0F $F0 $0F $0F $0F $F0 $0F $0F $0F
; Tile index $026
.db $F0 $0F $FF $0F $F0 $0F $FF $0F $F0 $0F $FF $0F $F0 $0F $FF $0F $F0 $0F $FF $0F $F0 $0F $FF $0F $F0 $0F $FF $0F $F0 $0F $FF $0F
; Tile index $027
.db $F0 $FF $FF $0F $F0 $FF $FF $0F $F0 $FF $FF $0F $F0 $FF $FF $0F $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $028
.db $F0 $FF $FF $00 $F0 $FF $FF $00 $F0 $FF $FF $00 $F0 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00
; Tile index $029
.db $0F $FF $FF $00 $0F $FF $FF $00 $0F $FF $FF $00 $0F $FF $FF $00 $0F $FF $FF $00 $0F $FF $FF $00 $0F $FF $FF $00 $0F $FF $FF $00
; Tile index $02A
.db $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $02B
.db $F0 $0F $0F $FF $F0 $0F $0F $FF $F0 $0F $0F $FF $F0 $0F $0F $FF $F0 $0F $0F $FF $F0 $0F $0F $FF $F0 $0F $0F $FF $F0 $0F $0F $FF
; Tile index $02C
.db $F0 $FF $0F $FF $F0 $FF $0F $FF $F0 $FF $0F $FF $F0 $FF $0F $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF
; Tile index $02D
.db $F0 $0F $FF $FF $F0 $0F $FF $FF $F0 $0F $FF $FF $F0 $0F $FF $FF $F0 $0F $FF $FF $F0 $0F $FF $FF $F0 $0F $FF $FF $F0 $0F $FF $FF
; Tile index $02E
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $0F $F0 $F0 $F0 $0F $F0 $F0 $F0 $0F $F0 $F0 $F0 $0F $F0 $F0 $F0
; Tile index $02F
.db $F0 $0F $0F $0F $F0 $0F $0F $0F $F0 $0F $0F $0F $F0 $0F $0F $0F $F0 $0F $0F $0F $F0 $0F $0F $0F $F0 $0F $0F $0F $F0 $0F $0F $0F
; Tile index $030
.db $00 $F0 $F0 $F0 $00 $F0 $F0 $F0 $00 $F0 $F0 $F0 $00 $F0 $F0 $F0 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $031
.db $0F $00 $00 $00 $0F $00 $00 $00 $0F $00 $00 $00 $0F $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $032
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $0F $FF $F0 $F0 $0F $FF $F0 $F0 $0F $FF $F0 $F0 $0F $FF $F0 $F0
; Tile index $033
.db $F0 $FF $0F $0F $F0 $FF $0F $0F $F0 $FF $0F $0F $F0 $FF $0F $0F $F0 $FF $0F $0F $F0 $FF $0F $0F $F0 $FF $0F $0F $F0 $FF $0F $0F
; Tile index $034
.db $0F $FF $00 $00 $0F $FF $00 $00 $0F $FF $00 $00 $0F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00
; Tile index $035
.db $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $0F $F0 $FF $F0 $0F $F0 $FF $F0 $0F $F0 $FF $F0 $0F $F0 $FF $F0
; Tile index $036
.db $00 $F0 $FF $F0 $00 $F0 $FF $F0 $00 $F0 $FF $F0 $00 $F0 $FF $F0 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $037
.db $0F $00 $FF $00 $0F $00 $FF $00 $0F $00 $FF $00 $0F $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $038
.db $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $F0 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $039
.db $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $03A
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $0F $F0 $FF $FF $0F $F0 $FF $FF $0F $F0 $FF $FF $0F $F0 $FF $FF
; Tile index $03B
.db $00 $F0 $FF $FF $00 $F0 $FF $FF $00 $F0 $FF $FF $00 $F0 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $03C
.db $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $0F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
